"""add embedded_content_hash to documents

Revision ID: 8033c30d4184
Revises: c2fac9b7afe8
Create Date: 2026-07-14 11:38:26.098104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8033c30d4184'
down_revision: Union[str, Sequence[str], None] = 'c2fac9b7afe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('embedded_content_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'embedded_content_hash')
    # ### end Alembic commands ###
