"""create documents and document_chunks tables

Revision ID: c2fac9b7afe8
Revises: 82afcfd451ad
Create Date: 2026-07-14 11:14:46.314383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2fac9b7afe8'
down_revision: Union[str, Sequence[str], None] = '82afcfd451ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.Enum('admissions', 'registration', 'orientation', 'housing', 'dining', 'financial_aid', 'scholarships', 'student_employment', 'international_student_services', 'visa', 'cpt', 'opt', 'technology_services', 'libraries', 'transportation', 'health_insurance', 'campus_recreation', 'student_organizations', 'academic_calendar', 'course_registration', name='topic', native_enum=False, length=64), nullable=False),
    sa.Column('source_type', sa.Enum('html', 'pdf', name='sourcetype', native_enum=False, length=16), nullable=False),
    sa.Column('student_types', sa.ARRAY(sa.Enum('freshman', 'transfer', 'graduate', 'international', name='studenttype', native_enum=False, length=32)), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_url'), 'documents', ['url'], unique=True)
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_number')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_documents_url'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
